/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PollResponse {
  'status' : PredictionStatus,
  'outputUrl' : [] | [string],
}
export type PollResult = { 'ok' : PollResponse } |
  { 'err' : SwapError };
export type PredictionStatus = { 'starting' : null } |
  { 'processing' : null } |
  { 'failed' : null } |
  { 'succeeded' : null };
export type SwapError = { 'invalidInput' : string } |
  { 'networkError' : string } |
  { 'notFound' : null } |
  { 'apiError' : string };
export type SwapResult = { 'ok' : string } |
  { 'err' : SwapError };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'pollFaceSwap' : ActorMethod<[string], PollResult>,
  'startFaceSwap' : ActorMethod<[string, string], SwapResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];