/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PredictionStatus = IDL.Variant({
  'starting' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
  'succeeded' : IDL.Null,
});
export const PollResponse = IDL.Record({
  'status' : PredictionStatus,
  'outputUrl' : IDL.Opt(IDL.Text),
});
export const SwapError = IDL.Variant({
  'invalidInput' : IDL.Text,
  'networkError' : IDL.Text,
  'notFound' : IDL.Null,
  'apiError' : IDL.Text,
});
export const PollResult = IDL.Variant({
  'ok' : PollResponse,
  'err' : SwapError,
});
export const SwapResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : SwapError });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'pollFaceSwap' : IDL.Func([IDL.Text], [PollResult], []),
  'startFaceSwap' : IDL.Func([IDL.Text, IDL.Text], [SwapResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PredictionStatus = IDL.Variant({
    'starting' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
    'succeeded' : IDL.Null,
  });
  const PollResponse = IDL.Record({
    'status' : PredictionStatus,
    'outputUrl' : IDL.Opt(IDL.Text),
  });
  const SwapError = IDL.Variant({
    'invalidInput' : IDL.Text,
    'networkError' : IDL.Text,
    'notFound' : IDL.Null,
    'apiError' : IDL.Text,
  });
  const PollResult = IDL.Variant({ 'ok' : PollResponse, 'err' : SwapError });
  const SwapResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : SwapError });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'pollFaceSwap' : IDL.Func([IDL.Text], [PollResult], []),
    'startFaceSwap' : IDL.Func([IDL.Text, IDL.Text], [SwapResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };