/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PollResult = {
    __kind__: "ok";
    ok: PollResponse;
} | {
    __kind__: "err";
    err: SwapError;
};
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type SwapResult = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: SwapError;
};
export type SwapError = {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "networkError";
    networkError: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "apiError";
    apiError: string;
};
export interface PollResponse {
    status: PredictionStatus;
    outputUrl?: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum PredictionStatus {
    starting = "starting",
    processing = "processing",
    failed = "failed",
    succeeded = "succeeded"
}
export interface backendInterface {
    pollFaceSwap(predictionId: string): Promise<PollResult>;
    startFaceSwap(faceImageUrl: string, targetImageUrl: string): Promise<SwapResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { PollResponse as _PollResponse, PollResult as _PollResult, PredictionStatus as _PredictionStatus, SwapError as _SwapError, SwapResult as _SwapResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async pollFaceSwap(arg0: string): Promise<PollResult> {
        if (this.processError) {
            try {
                const result = await this.actor.pollFaceSwap(arg0);
                return from_candid_PollResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pollFaceSwap(arg0);
            return from_candid_PollResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async startFaceSwap(arg0: string, arg1: string): Promise<SwapResult> {
        if (this.processError) {
            try {
                const result = await this.actor.startFaceSwap(arg0, arg1);
                return from_candid_SwapResult_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startFaceSwap(arg0, arg1);
            return from_candid_SwapResult_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_PollResponse_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PollResponse): PollResponse {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_PollResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PollResult): PollResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_PredictionStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PredictionStatus): PredictionStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SwapError_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SwapError): SwapError {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SwapResult_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SwapResult): SwapResult {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _PredictionStatus;
    outputUrl: [] | [string];
}): {
    status: PredictionStatus;
    outputUrl?: string;
} {
    return {
        status: from_candid_PredictionStatus_n5(_uploadFile, _downloadFile, value.status),
        outputUrl: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.outputUrl))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: _SwapError;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: SwapError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_SwapError_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PollResponse;
} | {
    err: _SwapError;
}): {
    __kind__: "ok";
    ok: PollResponse;
} | {
    __kind__: "err";
    err: SwapError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PollResponse_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_SwapError_n8(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    starting: null;
} | {
    processing: null;
} | {
    failed: null;
} | {
    succeeded: null;
}): PredictionStatus {
    return "starting" in value ? PredictionStatus.starting : "processing" in value ? PredictionStatus.processing : "failed" in value ? PredictionStatus.failed : "succeeded" in value ? PredictionStatus.succeeded : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidInput: string;
} | {
    networkError: string;
} | {
    notFound: null;
} | {
    apiError: string;
}): {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "networkError";
    networkError: string;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "apiError";
    apiError: string;
} {
    return "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "networkError" in value ? {
        __kind__: "networkError",
        networkError: value.networkError
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "apiError" in value ? {
        __kind__: "apiError",
        apiError: value.apiError
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
